var hermes;var hermesInstance=null;var statusInterval=null;let hermesReady=null;if(typeof(WebSocket)!=="undefined"){connectToHermes();function connectToHermes(){var wsURL="ws"+((location.protocol==="https:")?"s":"")+"://"+location.host+"/hermes/";hermes=new WebSocket(wsURL);hermes.onopen=function(){if(statusInterval!==null){clearInterval(statusInterval);statusInterval=null;}
$('#status').trigger("hermes:connect");};hermes.onmessage=function(data){var msg=JSON.parse(data.data);switch(msg.type){case "ready":hermesReady=true;$('#status').trigger("hermes:ready");break;case "status":var status=JSON.parse(msg.message);showStatus(status);break;case "queue_reduced":var queue=JSON.parse(msg.message);$('#status').trigger("queue:reduced",[queue]);break;case "backup_progress":if(window.backupProgressUpdate){backupProgressUpdate(JSON.parse(msg.message));}
break;case "welcome":hermesInstance=msg.message;break;case "reload":location.reload();break;default:$('#status').trigger("hermes:message",[msg]);break;}};hermes.onclose=function(){console.log("Lost connection to hermes... Reconnecting...");if(statusInterval===null){statusInterval=setInterval(updateStatusAndTryHermes,10*1000+Math.round(Math.random()*20*1000));}
hermesReady=false;$('#status').trigger("hermes:disconnect");};hermes.onerror=function(error){console.error(error);};}
function updateStatusAndTryHermes(){if(hermes.readyState===3){connectToHermes();}else if(statusInterval!==null){clearInterval(statusInterval);statusInterval=null;}}}else{statusInterval=setInterval(updateStatus,10*1000);}
function updateStatus(callback){aget('/panel/ajax/status.php',function(data){var status=JSON.parse(data);showStatus(status);if(typeof(callback)!=="undefined"){callback(status);}});}
function showStatus(status){$('.status').attr('class','status '+status.class);$('.navigation-server').attr('class','navigation-server '+status.class);$('.mobile-statusicon').attr('class','mobile-statusicon '+status.class);$('.statuslabel > i').fa("fas",status.icon);$('.statusicon > i').fa("fas",status.icon);$('.statuslabel .statuslabel-label').text(LANGUAGE[status.lang]);$('.statusplayerbadge').text(status.players+"/"+status.slots);updateProblemCount(status.problems);if(status.message.text.trim()==""&&$('#global-message-container').html().trim()!=""){$('.global-message').slideUp(100);$('#global-message-container').html("");}else if(status.message.text.trim()!=""&&$('#global-message-container').html().trim()===""){$('#global-message-container').html('<div style="display: none;" class="global-message '+status.message.class+'">'+status.message.text+'</div>');updateCountH();$('.global-message').slideDown(100);}
if(lastStatus!==null){if(status.class=='queueing'&&status.queue.pending=='pending'){if(typeof(lastStatus.queue)=="undefined"||lastStatus.queue.pending!='pending'){if(typeof ironRVPresent!=="undefined"&&ironRVPresent===true){confirm();}else{playSound('confirm');sendNotification(LANGUAGE.confirmnotification,confirm);}}}
if(status.class=='online'&&lastStatus.class!='online'){playSound('start');sendNotification(LANGUAGE.onlinenotification);}}
lastStatus=status;$('#status').trigger("status:update",[status]);}
function updateProblemCount(count){$('.navigation-log-problems-badge').text(count);if(count>0){$('.navigation-log-problems-badge').show();}else{$('.navigation-log-problems-badge').hide();}}
function confirm(callback){aget('/panel/ajax/confirm.php',function(){if(typeof(callback)==="function"){callback();}});}