if(!String.prototype.padStart){String.prototype.padStart=function(length,str){if(this.length>=length){return this;}
str=str||' ';return(new Array(Math.ceil((length-this.length)/str.length)+1).join(str)).substr(0,(length-this.length))+this;};}
function playSound(sound){var audio=new Audio('/panel/sound/'+sound+'.mp3');audio.play();}
function requestNotificationPermissions(){if(isNewNotificationSupported()){if(Notification.permission!=="granted"){alert({text:LANGUAGE.allownotifications,buttons:[{label:LANGUAGE.okay,color:"green",icon:"check",callback:"requestnotification()"},"cancel"]});}}}
function requestnotification(){hideAlert();if(isNewNotificationSupported()){try{Notification.requestPermission().then(function(result){if(result==='default'||result==='denied'){return;}});}catch(error){if(error instanceof TypeError){Notification.requestPermission(function(){if(Notification.permission=="granted"){}else{return;}});}else{throw error;}}}}
function sendNotification(text,callback){try{if(isNewNotificationSupported()){if(Notification.permission=="granted"){var notification=new Notification(BRAND_NAME,{icon:NOTIFICATION_ICON,body:text,});notification.onclick=function(){notification.close();window.focus();if(typeof(callback)!=="undefined"){callback(status);}};}}}catch(e){alert({text:LANGUAGE.error+"<br /><br />"+e.message,color:"red",buttons:["okay"]});}}
function isNewNotificationSupported(){if(!window.Notification||!Notification.requestPermission){return false;}
if(location.hostname.endsWith(".local")){return false;}
if(Notification.permission=='granted'){return true;}
try{new Notification('');}catch(e){if(e.name=='TypeError')
return false;}
return true;}
function setCookie(name,value,days){if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));var expires="; expires="+date.toGMTString();}
else var expires="";document.cookie=name+"="+value+expires+"; path=/";}
function getCookie(name){var nameEQ=name+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1,c.length);if(c.indexOf(nameEQ)==0)return c.substring(nameEQ.length,c.length);}
return null;}
function eraseCookie(name){setCookie(name,"",-1);}
function htmlentities(str){let el=document.createElement('div');el.textContent=str;return el.innerHTML.replace(/["']/g,m=>m==='"'?"&quot;":"&apos;");}
function copyToClipboard(text){let range=document.createRange();var tmpElem=$('<div>');tmpElem.css({position:"absolute",left:"-1000px",top:"-1000px",});tmpElem.text(text);$("body").append(tmpElem);range.selectNodeContents(tmpElem.get(0));let selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);document.execCommand("copy",false,null);tmpElem.remove();}
function humanReadableSize(bytes,decimals=2,base=1024){let size=[' B',' kB',' MB',' GB',' TB',' PB',' EB',' ZB',' YB'];let factor=Math.floor((String(bytes).length-1)/3);return `${(bytes/Math.pow(base,factor)).toFixed(2)}`+(size[factor]||'');}
function updateCountH(){$('[data-counth]').each(function(i,element){element=$(element);let finish=element.data("counth");let timeLeft=finish-Math.round(Date.now()/1000);let hoursLeft=Math.floor(timeLeft/60/60);let text;if(hoursLeft>1){text="in ca. "+hoursLeft+" hours";}else if(hoursLeft===1){text="in ca. 1 hour";}else{text="in less than 1 hour";}
element.text(text);});}
function placeCaretAtEnd(el){el.focus();if(typeof window.getSelection!="undefined"&&typeof document.createRange!="undefined"){let range=document.createRange();range.selectNodeContents(el);range.collapse(false);let sel=window.getSelection();sel.removeAllRanges();sel.addRange(range);}else if(typeof document.body.createTextRange!="undefined"){let textRange=document.body.createTextRange();textRange.moveToElementText(el);textRange.collapse(false);textRange.select();}}
$(document).ready(function(){$('.select .current').click(function(e){$(this).parent().find('.select-options').slideToggle(100,function(){$(this).parent().find(".option-category-options").hide();});});$('.select .select-options .option').click(function(e){var select=$(this).closest(".select");if(!$(this).hasClass("option-category")){let value=$(this).data("value");select.find(".current").data("value",value);select.find(".current").attr("data-value",value);select.find(".current").text($(this).text());select.find(".select-options").slideToggle(100,function(){select.find(".option-category-options").hide();});let event=document.createEvent('HTMLEvents');event.initEvent('change',true,true);select.trigger("change");select.get(0).dispatchEvent(event);}else{$(this).find(".option-category-options").show();}});$('.option-category-back').click(function(e){e.stopPropagation();$(this).closest(".option-category-options").hide();});$('.js-date').each(function(){var date=new Date($(this).data('date')*1000);$(this).text(date.toLocaleDateString());});$('.js-date-time').each(function(){var date=new Date($(this).data('date')*1000);$(this).text(date.toLocaleString());});$('.input-number-up').mousedown(function(){const input=$(this).parent().parent().find('input');let value=parseInt(input.val());let step=parseInt(input.attr('step'));let target=value+step;if(target<input.attr('max')){input.val(target);}else{input.val(input.attr('max'));}});$('.input-number-down').mousedown(function(){const input=$(this).parent().parent().find('input');let value=parseInt(input.val());let step=parseInt(input.attr('step'));let target=value-step;if(target>input.attr('min')){input.val(target);}else{input.val(input.attr('min'));}});});